export const driverSchema = {
	type: 'object',
	properties: {
		id: { type: 'string' },
		fullName: { type: 'string' },
		email: { type: 'string', format: 'email' },
		password: { type: 'string', minLength: 6 },
		phone: { type: 'string', minLength: 10, maxLength: 15 },
		profilePicture: { type: 'string' },
		vehicleType: { type: 'string' },
		vehicleDetails: { type: 'string' },
		licenseNumber: { type: 'string' },
		licenseExpiryDate: { type: 'string', format: 'date' },
		paymentMethod: { type: 'string' },
		paymentHistory: { type: 'array', items: { type: 'object' } },
		rideHistory: { type: 'array', items: { type: 'object' } },
		deliveryHistory: { type: 'array', items: { type: 'object' } },
		rating: { type: 'number', minimum: 0, maximum: 5 },
	},
	required: [
		'fullName',
		'email',
		'password',
		'phone',
		'vehicleType',
		'vehicleDetails',
		'licenseNumber',
		'licenseExpiryDate',
	],
	additionalProperties: false,
};
